/**
 * CommentSection Component
 * 
 * A comprehensive component for displaying and managing comments and discussions.
 */

export { default } from './CommentSection';

// Re-export constants from constants.js
export {
  COMMENT_SECTION_CLASS,
  COMMENT_SECTION_HEADER_CLASS,
  COMMENT_SECTION_BODY_CLASS,
  COMMENT_SECTION_FOOTER_CLASS,
  COMMENT_SECTION_TITLE_CLASS,
  COMMENT_SECTION_SUBTITLE_CLASS,
  COMMENT_SECTION_ACTIONS_CLASS,
  COMMENT_SECTION_COMMENT_CLASS,
  COMMENT_SECTION_COMMENT_HEADER_CLASS,
  COMMENT_SECTION_COMMENT_BODY_CLASS,
  COMMENT_SECTION_COMMENT_FOOTER_CLASS,
  COMMENT_SECTION_COMMENT_AVATAR_CLASS,
  COMMENT_SECTION_COMMENT_AUTHOR_CLASS,
  COMMENT_SECTION_COMMENT_TIMESTAMP_CLASS,
  COMMENT_SECTION_COMMENT_CONTENT_CLASS,
  COMMENT_SECTION_COMMENT_ACTIONS_CLASS,
  COMMENT_SECTION_FORM_CLASS,
  COMMENT_SECTION_FORM_TEXTAREA_CLASS,
  COMMENT_SECTION_FORM_ACTIONS_CLASS,
  COMMENT_SECTION_EMPTY_CLASS,
  COMMENT_SECTION_LOADING_CLASS,
  COMMENT_SECTION_ERROR_CLASS,
  COMMENT_SECTION_VARIANTS,
  COMMENT_SECTION_SIZES,
  COMMENT_SECTION_SORT_OPTIONS,
  COMMENT_SECTION_COMMENT_TYPES,
  COMMENT_SECTION_MODIFIERS
} from './constants';
