/**
 * NotificationCenter Component Export
 * 
 * This file exports the NotificationCenter component and its related constants.
 */

import NotificationCenter from './NotificationCenter';
import {
  NOTIFICATION_CENTER_VARIANTS,
  NOTIFICATION_CENTER_SIZES,
  NOTIFICATION_CENTER_MODIFIERS,
  NOTIFICATION_CENTER_SECTIONS,
  NOTIFICATION_CENTER_ARIA,
  NOTIFICATION_CENTER_DATA_ATTRIBUTES,
  NOTIFICATION_CENTER_CLASS_NAMES,
  NOTIFICATION_TYPES,
  NOTIFICATION_STATES,
  NOTIFICATION_FILTER_TYPES,
  NOTIFICATION_SORT_TYPES
} from './constants';

// Export the component as default
export default NotificationCenter;

// Export constants for external use
export {
  NOTIFICATION_CENTER_VARIANTS,
  NOTIFICATION_CENTER_SIZES,
  NOTIFICATION_CENTER_MODIFIERS,
  NOTIFICATION_CENTER_SECTIONS,
  NOTIFICATION_CENTER_ARIA,
  NOTIFICATION_CENTER_DATA_ATTRIBUTES,
  NOTIFICATION_CENTER_CLASS_NAMES,
  NOTIFICATION_TYPES,
  NOTIFICATION_STATES,
  NOTIFICATION_FILTER_TYPES,
  NOTIFICATION_SORT_TYPES
};
