/**
 * MilestoneTracker Component
 * 
 * A component for displaying and tracking milestones in a project or activity.
 */

export { default } from './MilestoneTracker';

// Re-export constants from constants.js
export {
  MILESTONE_TRACKER_CLASS,
  MILESTONE_TRACKER_HEADER_CLASS,
  MILESTONE_TRACKER_TITLE_CLASS,
  MILESTONE_TRACKER_SUBTITLE_CLASS,
  MILESTONE_TRACKER_BODY_CLASS,
  MILESTONE_TRACKER_FOOTER_CLASS,
  MILESTONE_TRACKER_TIMELINE_CLASS,
  MILESTONE_TRACKER_MILESTONE_CLASS,
  MILESTONE_TRACKER_MILESTONE_ICON_CLASS,
  MILESTONE_TRACKER_MILESTONE_CONTENT_CLASS,
  MILESTONE_TRACKER_MILESTONE_TITLE_CLASS,
  MILESTONE_TRACKER_MILESTONE_DATE_CLASS,
  MILESTONE_TRACKER_MILESTONE_DESCRIPTION_CLASS,
  MILESTONE_TRACKER_MILESTONE_CONNECTOR_CLASS,
  MILESTONE_TRACKER_PROGRESS_CLASS,
  MILESTONE_TRACKER_ACTIONS_CLASS,
  MILESTONE_TRACKER_VARIANTS,
  MILESTONE_TRACKER_SIZES,
  MILESTONE_STATUS,
  MILESTONE_TRACKER_MODIFIERS
} from './constants';
