/**
 * DependencyGraph Component
 * 
 * A component for visualizing dependencies between nodes in a graph structure.
 */

export { default } from './DependencyGraph';

// Re-export constants from constants.js
export {
  DEPENDENCY_GRAPH_CLASS,
  DEPENDENCY_GRAPH_HEADER_CLASS,
  DEPENDENCY_GRAPH_TITLE_CLASS,
  DEPENDENCY_GRAPH_SUBTITLE_CLASS,
  DEPENDENCY_GRAPH_BODY_CLASS,
  DEPENDENCY_GRAPH_FOOTER_CLASS,
  DEPENDENCY_GRAPH_CANVAS_CLASS,
  DEPENDENCY_GRAPH_NODE_CLASS,
  DEPENDENCY_GRAPH_NODE_CONTENT_CLASS,
  DEPENDENCY_GRAPH_NODE_TITLE_CLASS,
  DEPENDENCY_GRAPH_NODE_DESCRIPTION_CLASS,
  DEPENDENCY_GRAPH_EDGE_CLASS,
  DEPENDENCY_GRAPH_CONTROLS_CLASS,
  DEPENDENCY_GRAPH_LEGEND_CLASS,
  DEPENDENCY_GRAPH_ACTIONS_CLASS,
  DEPENDENCY_GRAPH_VARIANTS,
  DEPENDENCY_GRAPH_SIZES,
  DEPENDENCY_NODE_STATUS,
  DEPENDENCY_EDGE_TYPES,
  DEPENDENCY_GRAPH_LAYOUTS,
  DEPENDENCY_GRAPH_MODIFIERS
} from './constants';
